version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://matrix_user:securepassword123@db/destiny_matrix
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matrix_user -d destiny_matrix"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: matrix_user
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: destiny_matrix
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db-init:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: python backend/app/db_init.py
    environment:
      - DATABASE_URL=postgresql://matrix_user:securepassword123@db/destiny_matrix

volumes:
  postgres_data: